### PR TITLE
Allow multiple account creation

### PR DESCRIPTION
**Pull request by Bitti09**
Ported from  @ryanza  commit
Source commit: https://github.com/ryanza/PTCAccount/commit/752d8adf6afec36f56629c39e1438592ca3d0c44

Tested  on Ubuntu 16.04 (elementary os)

---

This change is [Reviewable](https://reviewable.io/reviews/kitryn/ptcaccount2/9)

### CODE REVIEW

**Comment by jxjftw** [comment]
Then from there, have the master list print into a csv :D

**Comment by Kitryn** [comment]
The reason I left it out during the port was that I hadn't written exception handling at the time, say if the user specifies multiple accounts but also provides a username; the same goes for if the user provides an email (though this can be solved by the +tag option from the original that I left out in the port as well).

I'm ready to merge if a suffix is appended to username if the user provides a username (prevents duplicate username error), also if the tag option is ported in as well; though the latter has to be made clear in documentation that it doesn't work with all email services. I'm only aware it works with gmail so far, but never tested with other providers.

Also my birthday date validation is not very good right now, so the help message should be changed back to specifying YYYY-MM-DD is required at least until I fix the date validation.

Thanks!

**Comment by Baklap4** [comment]
I'd love to see this within the master branch. I've used it for quite some time as a patch and working as it should be!

**Comment by Kitryn** [comment]
Merging into a patch branch until I fix the aforementioned issues.

EDIT: Fixed and merged into master.

**Pull request merged**
