### PR TITLE
Add domain email option and fix dob

### PR DESCRIPTION
**Pull request by Zoruk**

### CODE REVIEW

**Comment by nik-humphries** [comment]
Does this work when the website asks for DOB in DD-MM-YYYY format? I did a different fix that didn't clone the element and just rearranged the DOB input.

**Comment by Zoruk** [comment]
Nope it's disable the javascript date picker

**Comment by Kitryn** [comment]
@Shadowfish26 Does the website ask for DD-MM-YYYY format when you're in a different region? I've tried changing the region on the website and it still asks for the standard YYYY-MM-DD?

@Zoruk the script works even with the javascript date picker in place, which is why I didn't remove it. Also the domain customisation should be done by the script that calls random_account, rather than random_account itself, as it is not random_account's responsibility to generate specific emails. But thanks for the request!

**Comment by nik-humphries** [comment]
I am currently in Spain/Europe so being in a different region may alter the input.

Here is a grab of the form - https://gyazo.com/7a10e0d44089c2956c470cef03370b5a

The 3 date elements are part of one larger element. Each is clickable and can be altered by either typing or using a set of arrows that appear onscreen. The URL is https://club.pokemon.com/us/pokemon-trainer-club/sign-up/ which would imply a "US" site.

If you submit a DOB and then return to the first page without completing the account setup, the format becomes YYYY-MM-DD as so - https://gyazo.com/658a4143a31b9cf3ddc5d8996aaa3c76 and is greyed out requiring you to change the readonly attribute of the field.

It is possible that it gives you a region specific page based on IP.

Another comment is that I had to remove the element.clear command as the form I am presented with is not clearable.

**Comment by Kitryn** [comment]
Interesting, I wonder if it's a region-settings thing on local computers. I VPN-ed to both UK and Spain and both pages show YYYY-MM-DD on my screen, even if I tried changing the URL to /uk/ instead of /us/.

Does YYYY-MM-DD work when you submit it with your page, or does the website throw an error? Could you open up a new issue, and we can discuss it there? Thanks!

**Pull request closed without merging**
